# set version
version: 2.1

# define orbs
orbs:
  docker: circleci/docker@2.4.0
  go: circleci/go@1.9.0

# define jobs
jobs:
  # lint dockerfile job
  lint-dockerfile:
    # define executor use hadolint
    executor: docker/machine
    # define steps
    steps:
      - checkout # Check out code from the configured version control system.
      - docker/hadolint: # Run hadolint to lint Dockerfiles.
          dockerfiles: Dockerfile # Specify Dockerfiles to lint.
          trusted-registries: 'docker.io,gcr.io' # Specify trusted registries.
  
  # test job
  test-app:
    # define executor
    executor: go/default
    # define steps
    steps:
      - checkout # Check out code from the configured version control system.
      - go/load-cache # Load cached Go modules.
      - go/mod-download # Run 'go mod download'.
      - go/save-cache # Save Go modules to cache.
      - run: # Run tests.
          name: Test
          command: go test -v -short --count=1 $(go list ./...)

  # build job
  build-app-karsajobs:
    # define executor
    executor: docker/machine
    # define steps
    steps:
      - checkout
      - run:
          name: Build and push image to GitHub Packages
          command: ./build_push_image_karsajobs.sh

# define workflows
workflows:
  # run lint, test and build jobs
  lint:
    jobs:
      - lint-dockerfile
  test:
    jobs:
      - test-app
  build:
    jobs:
      - build-app-karsajobs
    